### ISSUE TITLE
Removing coupler_nml.atmos_nthreads option

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3gfs-fortran#153]
I don't think this is used by anything:
https://github.com/VulcanClimateModeling/fv3gfs-fortran/blob/10b6a78b3131a3f67e9b78a500d64eac93350929/FV3/coupler_main.F90#L112

The only reference is in some commented out code (which could also be deleted).

**Comment by oliverwm1** [comment]
@ofuhrer weren't you showing me results of how this option affected performance?

**Comment by ofuhrer** [comment]
Yes, this is not commented out code, but rather these are OpenMP compiler directives. The `!$` is a shorthand for conditional compilation. The code is only compiled, when OpenMP is enabled. To my knowledge, you are also compiling with OpenMP enabled.

**Comment by ofuhrer** [comment]
Oh gosh, my comment just got deleted. `!$` indicates code that is conditionally compiled when OpenMP compilation is activated (`-fopenmp` with GNU). These are not comments.

**Comment by nbren12** [comment]
I did see they are directives, but assumed the number of threads changes were isolated to between the `!$OMP PARALLEL NUM_THREADS(atmos_nthreads)` and `!$OMP END PARALLEL`. I didn't realize that this code actually got run:
```
!$      if(omp_get_thread_num() < atmos_nthreads/2 .OR. (.not. use_hyper_thread)) then  
!$         call set_cpu_affinity(base_cpu + omp_get_thread_num())
!$      else
!$         call set_cpu_affinity(base_cpu + omp_get_thread_num() + &
!$                               ncores_per_node - atmos_nthreads/2) 
!$      endif
!$      if (debug_affinity) then
!$        write(6,*) mpp_pe()," atmos  ",get_cpu_affinity(), base_cpu, omp_get_thread_num()
!$        call flush(6)
!$      endif
```
The pre-processor removes this if the model's not compiled openmp?

**Comment by ofuhrer** [comment]
Yes, this is code that is run when the code is compiled with OpenMP active.

**Comment by nbren12** [comment]
ok. thanks for the lesson. I'll close this.
