### ISSUE TITLE
Feature: add diagnostics for hydrometeors

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3gfs-fortran#182]
It would be nice to have column integrals for all the water species separately. As far as I can tell, there are no available column diagnostics for graupel, rain, or snow. The model only supports saving ice water path "iw", liquid water path "lw",  and precipitable water "pwat". 

cc @spencerkclark

**Comment by spencerkclark** [comment]
Yeah, I don't think there are.  I agree those would be nice -- it should be straightforward to add them.
