### ISSUE TITLE
Modify serialization image to have its compiled sources in /FV3

### ISSUE THREAD

**Issue by mcgibbon** [VulcanClimateModeling/fv3gfs-fortran#8]
If the serialized sources live in /FV3, the serialized model can be run with exactly the same interface as the non-serialized model. This simplifies testing and running the model images. The non-serialized code should be moved to another directory in the image so the sources can still be diff'd.

**Comment by rheacangeo** [comment]
You fixed this with https://github.com/VulcanClimateModeling/fv3gfs-fortran/commit/a2030c510013ade290c175b292e3bc5c5d0be704 I believe

**Comment by mcgibbon** [comment]
Good catch.
